@startuml openbeerdb
(Beerer) --> (Beer) : RATED(rating)
(Beerer) --> (Beer) : CHECKED(date, location, price)
(Beerer) --> (Beer) : COMMENTED(date, comment)
(Beerer) --> (Beerer) : IS_FRIEND_OF(since)
(Beer) --> (Brewery) : BREWED_AT
(Beer) --> (Category) : BEER_CATEGORY
(Beer) --> (Style) : BEER_STYLE
(Style) --> (Category) : STYLE_CATEGORY
(Brewery) --> (Geocode) : GEOLOCATED_AT
@enduml